FROM node:13.8.0-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV PORT 3000

COPY package*.json ./
RUN npm install --silent
RUN npm install react-script@3.0.1 -g --silent
COPY . .

CMD ["npm","start"]